# Generated by Django 6.1.1 on 2026-09-27 09:56

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import identity.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('system_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('DEVELOPER', 'Developer'), ('USER', 'User')], default='USER', help_text="Authorization tier embedded in the access token 'role' claim.", max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON claims/attributes propagated to relying parties.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'identity_user',
            },
            managers=[
                ('objects', identity.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('token_jti', models.CharField(editable=False, help_text='Unique token identifier (jti claim) that is now revoked.', max_length=64, primary_key=True, serialize=False)),
                ('invalidated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(help_text='Natural expiry of the revoked token; row is prunable after this.')),
                ('token_type', models.CharField(default='refresh', max_length=16)),
                ('reason', models.CharField(choices=[('LOGOUT', 'User logout'), ('LOGOUT_ALL', 'Global sign-out'), ('ROTATION', 'Refresh token rotated'), ('REUSE_DETECTED', 'Replay of a consumed refresh token'), ('ADMIN_REVOKE', 'Administrative revocation'), ('PASSWORD_CHANGE', 'Credential change')], default='LOGOUT', max_length=32)),
                ('user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blacklisted token',
                'verbose_name_plural': 'blacklisted tokens',
                'db_table': 'identity_blacklisted_token',
                'ordering': ('-invalidated_at',),
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['system_role', 'is_active'], name='idx_user_role_active'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['expires_at'], name='idx_blacklist_expires'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['user', 'invalidated_at'], name='idx_blacklist_user'),
        ),
    ]
